// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal_AP1.DAL;

#nullable disable

namespace ProyectoFinal_AP1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240808133034_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ProyectoFinal_AP1.Models.Entrenador", b =>
                {
                    b.Property<int>("IdEntrenador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdEntrenador");

                    b.ToTable("Entrenadores");
                });

            modelBuilder.Entity("ProyectoFinal_AP1.Models.Equipos", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Foto")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdEquipo");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ProyectoFinal_AP1.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Foto")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdProducto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ProyectoFinal_AP1.Models.Suscripcion", b =>
                {
                    b.Property<int>("IdSuscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("IdEntrenador")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precio")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdSuscripcion");

                    b.HasIndex("IdEntrenador");

                    b.ToTable("Suscripciones");
                });

            modelBuilder.Entity("ProyectoFinal_AP1.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaFinSuscripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaInicioSuscripcion")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdEntrenador")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdSuscripcion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SuscripcionIdSuscripcion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEntrenador");

                    b.HasIndex("SuscripcionIdSuscripcion");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoFinal_AP1.Models.Suscripcion", b =>
                {
                    b.HasOne("ProyectoFinal_AP1.Models.Entrenador", "Entrenador")
                        .WithMany("Suscripciones")
                        .HasForeignKey("IdEntrenador");

                    b.Navigation("Entrenador");
                });

            modelBuilder.Entity("ProyectoFinal_AP1.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoFinal_AP1.Models.Entrenador", "Entrenador")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEntrenador");

                    b.HasOne("ProyectoFinal_AP1.Models.Suscripcion", "Suscripcion")
                        .WithMany("Usuarios")
                        .HasForeignKey("SuscripcionIdSuscripcion");

                    b.Navigation("Entrenador");

                    b.Navigation("Suscripcion");
                });

            modelBuilder.Entity("ProyectoFinal_AP1.Models.Entrenador", b =>
                {
                    b.Navigation("Suscripciones");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProyectoFinal_AP1.Models.Suscripcion", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
